# Generated by Django 4.1.2 on 2022-10-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='request date')),
                ('city', models.CharField(max_length=200, verbose_name='city')),
                ('latitude', models.FloatField(max_length=50, verbose_name='latitude')),
                ('longitude', models.FloatField(max_length=50, verbose_name='longitude')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
                'ordering': ['date'],
            },
        ),
    ]
